const IPC = {
  REQUEST_API_INFO: 'REQUEST_API_INFO',
  API_INFO: 'API_INFO',
  PAIRING_CODE_AVAILABLE: 'PAIRING_CODE_AVAILABLE',
  PAIRING_TIMED_OUT: 'PAIRING_TIMED_OUT',
  PAIRING_COMPLETE: 'PAIRING_COMPLETE',
  PAIRING_CANCELLED: 'PAIRING_CANCELLED',
  RESET_APP: 'RESET_APP',
  DATA_IS_STALE: 'DATA_IS_STALE',
  PROTOCOL_IMPORT_START: 'PROTOCOL_IMPORT_START',
  PROTOCOL_IMPORT_SUCCESS: 'PROTOCOL_IMPORT_SUCCESS',
  PROTOCOL_IMPORT_FAILURE: 'PROTOCOL_IMPORT_FAILURE',
  SESSIONS_IMPORTED: 'SESSIONS_IMPORTED',
  SESSIONS_IMPORT_STARTED: 'SESSIONS_IMPORT_STARTED',
  SESSIONS_IMPORT_COMPLETE: 'SESSIONS_IMPORT_COMPLETE',
  NETWORK_STATUS_UPDATE: 'NETWORK_STATUS_UPDATE',
};

export default IPC;
