options:
  config-file: src/renderer/ui/.sass-lint.yml
files:
  include: 'src/**/*.s+(a|c)ss'
# Temporarily whitelist new prop (until next published sass-lint version)
rules:
  no-misspelled-properties:
    - 1
    - extra-properties:
      - overscroll-behavior
