language: node_js
branches:
  only:
    - master
node_js:
  - "8.5"
cache:
  directories:
    - node_modules # NPM packages
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libavahi-compat-libdnssd-dev
  - npm install
# before_install:
#   - if [[ $TRAVIS_OS_NAME == osx ]] && [[ $DIST == true ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install gnu-tar dpkg libicns graphicsmagick git-lfs lzip; fi
#   - if [[ $TRAVIS_OS_NAME == osx ]] && [[ $DIST == true ]]; then git lfs pull; fi
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build
