language: node_js
branches:
  only:
    - master
node_js:
  - "8.9.3"
cache:
  directories:
    - node_modules # NPM packages
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libavahi-compat-libdnssd-dev
  - npm install
before_install:
  - npm install -g npm@6.1.0
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build
