language: node_js
branches:
  only:
    - master
node_js:
  - "12.8.0"
cache:
  directories:
    - node_modules
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libavahi-compat-libdnssd-dev
  - npm install
jobs:
  include:
    - stage: test
      script: npm run lint && npm run sass-lint && npm run test && npm run build
